import http from 'node:http';

const host = process.env.HOST || '127.0.0.1';
const port = Number(process.env.FRONTEND_PORT || 3001);
const apiPort = Number(process.env.BACKEND_PORT || 3000);
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Shipping Refund Operations</title><style>body{font:16px system-ui;margin:0;background:#eef4f8;color:#152838}main{max-width:520px;margin:10vh auto;background:white;padding:3rem;border-radius:18px;box-shadow:0 18px 50px #2342}h1{color:#075985}.tag{display:inline-block;background:#d9f1ff;padding:.4rem .8rem;border-radius:999px}form,label{display:grid;gap:.5rem}form{gap:1rem}input,button{font:inherit;padding:.75rem;border:1px solid #91a5b5;border-radius:9px}button{cursor:pointer}.primary{background:#075985;color:white}.secondary{background:white;color:#075985}.error{color:#b91c1c}[hidden]{display:none}</style></head><body><main><section id="login"><span class="tag">Runtime-ready</span><h1>Shipping Refund Operations</h1><p>Authenticate to review shipment evidence and run the AI readiness check.</p><form id="login-form"><label>Email<input id="email" type="email" autocomplete="username" required></label><label>Password<input id="password" type="password" autocomplete="current-password" required></label><p id="error" class="error" role="alert"></p><button id="fill" type="button" class="secondary">Auto Fill Demo Credentials</button><button type="submit" class="primary">Sign In</button></form></section><section id="dashboard" hidden><span class="tag">Authenticated</span><h1>Shipping Refund Dashboard</h1><p id="identity"></p><p>Shipment evidence and protected refund operations are ready for review.</p></section></main><script>const login=document.querySelector('#login'),dashboard=document.querySelector('#dashboard'),email=document.querySelector('#email'),password=document.querySelector('#password'),error=document.querySelector('#error');document.querySelector('#fill').addEventListener('click',async()=>{error.textContent='';const response=await fetch('/api/auth/demo-credentials');if(!response.ok){error.textContent='Demo credentials are unavailable.';return}const value=await response.json();email.value=value.email;password.value=value.password});document.querySelector('#login-form').addEventListener('submit',async event=>{event.preventDefault();error.textContent='';const response=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.value,password:password.value})});if(!response.ok){error.textContent='Sign in failed.';return}const value=await response.json();sessionStorage.setItem('shipping_access_token',value.token);document.querySelector('#identity').textContent='Signed in as '+(value.user?.email||email.value);login.hidden=true;dashboard.hidden=false});</script></body></html>`;
const server = http.createServer((req, res) => {
  if (req.url?.startsWith('/api/')) {
    const proxy = http.request({ host, port: apiPort, path: req.url, method: req.method, headers: req.headers }, (upstream) => { res.writeHead(upstream.statusCode || 502, upstream.headers); upstream.pipe(res); });
    proxy.on('error', () => { res.writeHead(502); res.end('API unavailable'); });
    req.pipe(proxy); return;
  }
  res.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' }); res.end(html);
});
server.listen(port, host, () => console.log(`Shipping UI listening at http://${host}:${port}`));
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => server.close(() => process.exit(0)));
